In [115]:
!pip install tabulate
!pip install  --upgrade pip

Requirement already satisfied: tabulate in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (0.9.0)
Requirement already satisfied: pip in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (25.2)
Collecting pip
  Using cached pip-25.3-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-25.3-py3-none-any.whl (1.8 MB)

ERROR: To modify pip, please run the following command:
C:\Users\Admin\anaconda3\envs\nlp_env\python.exe -m pip install --upgrade pip

In [116]:
! pip install --upgrade langchain
! pip install langchain openai langchain-experimental

Requirement already satisfied: langchain in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (1.0.5)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.4 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain) (1.0.4)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain) (1.0.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain) (2.11.9)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (0.4.41)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (4.15.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.4->langchain) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.2)
Requirement already satisfied: langgraph-sdk<0.3.0,>=0.2.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.2.9)
Requirement already satisfied: xxhash>=3.5.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.0)
Requirement already satisfied: httpx>=0.25.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (3.11.4)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (0.24.0)
Requirement already satisfied: anyio in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (4.11.0)
Requirement already satisfied: certifi in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (2.5.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from anyio->httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (1.3.1)
Requirement already satisfied: langchain in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (1.0.5)
Requirement already satisfied: openai in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (2.7.2)
Requirement already satisfied: langchain-experimental in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (0.4.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.4 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain) (1.0.4)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain) (1.0.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain) (2.11.9)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (0.4.41)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (4.15.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.4->langchain) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.2)
Requirement already satisfied: langgraph-sdk<0.3.0,>=0.2.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.2.9)
Requirement already satisfied: xxhash>=3.5.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.0)
Requirement already satisfied: httpx>=0.25.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (3.11.4)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (0.24.0)
Requirement already satisfied: anyio in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (4.11.0)
Requirement already satisfied: certifi in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.1)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from openai) (0.12.0)
Requirement already satisfied: sniffio in c:\users\admin\appdata\roaming\python\python312\site-packages (from openai) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from openai) (4.67.1)
Requirement already satisfied: langchain-community<1.0.0,>=0.4.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-experimental) (0.4.1)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.0.0)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.0.43)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.13.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.11.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.4.1)
Requirement already satisfied: numpy>=1.26.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.26.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.0.0)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (2.5.0)
Requirement already satisfied: greenlet>=1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.2.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.1.0)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python312\site-packages (from tqdm>4->openai) (0.4.6)

In [117]:
#!pip install langchain
#!pip install watermark
#!pip install openai
!pip install langchain_experimental

Requirement already satisfied: langchain_experimental in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (0.4.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain_experimental) (1.0.4)
Requirement already satisfied: langchain-community<1.0.0,>=0.4.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain_experimental) (0.4.1)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain_experimental) (1.0.0)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain_experimental) (2.0.43)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain_experimental) (2.32.5)
Requirement already satisfied: PyYAML<7.0.0,>=5.3.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain_experimental) (6.0.3)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain_experimental) (3.13.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain_experimental) (9.1.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain_experimental) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain_experimental) (2.11.0)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain_experimental) (0.4.41)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain_experimental) (0.4.1)
Requirement already satisfied: numpy>=1.26.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain_experimental) (1.26.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (1.0.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (2.11.9)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain_experimental) (1.33)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain_experimental) (25.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.0->langchain_experimental) (4.15.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.0->langchain_experimental) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (3.11.4)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (1.0.0)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (0.24.0)
Requirement already satisfied: anyio in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (4.11.0)
Requirement already satisfied: certifi in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (1.0.9)
Requirement already satisfied: idna in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-classic<2.0.0,>=1.0.0->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (0.4.1)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (1.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from requests<3.0.0,>=2.32.5->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from requests<3.0.0,>=2.32.5->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (2.5.0)
Requirement already satisfied: greenlet>=1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (3.2.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (1.1.0)
Requirement already satisfied: sniffio>=1.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from anyio->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community<1.0.0,>=0.4.0->langchain_experimental) (1.3.1)

In [118]:
pip install langchain-openai

Requirement already satisfied: langchain-openai in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (1.0.2)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-openai) (1.0.4)
Requirement already satisfied: openai<3.0.0,>=1.109.1 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-openai) (2.7.2)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-openai) (0.12.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.2->langchain-openai) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.2->langchain-openai) (0.4.41)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.2->langchain-openai) (25.0)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.2->langchain-openai) (2.11.9)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.2->langchain-openai) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.2->langchain-openai) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.2->langchain-openai) (4.15.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.2->langchain-openai) (3.0.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.2->langchain-openai) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.2->langchain-openai) (3.11.4)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.2->langchain-openai) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.2->langchain-openai) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.2->langchain-openai) (0.24.0)
Requirement already satisfied: anyio in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.2->langchain-openai) (4.11.0)
Requirement already satisfied: certifi in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.2->langchain-openai) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.2->langchain-openai) (1.0.9)
Requirement already satisfied: idna in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.2->langchain-openai) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.2->langchain-openai) (0.16.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (0.12.0)
Requirement already satisfied: sniffio in c:\users\admin\appdata\roaming\python\python312\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (4.67.1)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.2->langchain-openai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.2->langchain-openai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.2->langchain-openai) (0.4.1)
Requirement already satisfied: regex>=2022.1.18 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2024.11.6)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.2->langchain-openai) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.2->langchain-openai) (2.5.0)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python312\site-packages (from tqdm>4->openai<3.0.0,>=1.109.1->langchain-openai) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [119]:
import os
import warnings
warnings.filterwarnings("ignore")

In [120]:
from langchain_openai import ChatOpenAI

In [121]:
llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

In [122]:
from langchain_openai import ChatOpenAI
from langchain_experimental.agents import create_pandas_dataframe_agent
import pandas as pd
import os

In [123]:
from langchain_openai import ChatOpenAI

In [124]:
#from langchain.agents import create_pandas_dataframe_agent
from langchain_experimental.agents import create_pandas_dataframe_agent

In [125]:
agent = create_pandas_dataframe_agent(
    llm, 
    df, 
    verbose=True,
    agent_type="openai-tools",
    allow_dangerous_code=True
    )

In [126]:
import pandas as pd

In [127]:
os.environ["OPENAI_API_KEY"] = "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"

In [128]:
#url = "https://raw.githubusercontent.com/sudarshan-koirala/Logistic-Regression-for-Titanic-Dataset/master/Train_Titanic.csv"
df=pd.read_csv(r'C:\Users\Admin\AVScode\AI\GENAI\titanic dataset.csv')
print(df.shape)
df.head()

(891, 12)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [129]:
pip uninstall -y langchain langchain-openai langchain-experimental

Found existing installation: langchain 1.0.5
Uninstalling langchain-1.0.5:
  Successfully uninstalled langchain-1.0.5
Found existing installation: langchain-openai 1.0.2
Uninstalling langchain-openai-1.0.2:
  Successfully uninstalled langchain-openai-1.0.2
Found existing installation: langchain-experimental 0.4.0
Uninstalling langchain-experimental-0.4.0:
  Successfully uninstalled langchain-experimental-0.4.0
Note: you may need to restart the kernel to use updated packages.

In [130]:
pip install -U langchain langchain-openai langchain-experimental

Collecting langchain
  Using cached langchain-1.0.5-py3-none-any.whl.metadata (4.9 kB)
Collecting langchain-openai
  Using cached langchain_openai-1.0.2-py3-none-any.whl.metadata (1.8 kB)
Collecting langchain-experimental
  Using cached langchain_experimental-0.4.0-py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.4 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain) (1.0.4)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain) (1.0.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain) (2.11.9)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (0.4.41)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (4.15.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.4->langchain) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.2)
Requirement already satisfied: langgraph-sdk<0.3.0,>=0.2.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.2.9)
Requirement already satisfied: xxhash>=3.5.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.0)
Requirement already satisfied: httpx>=0.25.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (3.11.4)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (0.24.0)
Requirement already satisfied: anyio in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (4.11.0)
Requirement already satisfied: certifi in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.1)
Requirement already satisfied: openai<3.0.0,>=1.109.1 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-openai) (2.7.2)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-openai) (0.12.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (0.12.0)
Requirement already satisfied: sniffio in c:\users\admin\appdata\roaming\python\python312\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (4.67.1)
Requirement already satisfied: regex>=2022.1.18 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2024.11.6)
Requirement already satisfied: langchain-community<1.0.0,>=0.4.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-experimental) (0.4.1)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.0.0)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.0.43)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.13.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.11.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.4.1)
Requirement already satisfied: numpy>=1.26.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.26.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.0.0)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (2.5.0)
Requirement already satisfied: greenlet>=1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.2.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.1.0)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python312\site-packages (from tqdm>4->openai<3.0.0,>=1.109.1->langchain-openai) (0.4.6)
Using cached langchain-1.0.5-py3-none-any.whl (93 kB)
Using cached langchain_openai-1.0.2-py3-none-any.whl (81 kB)
Using cached langchain_experimental-0.4.0-py3-none-any.whl (209 kB)
Installing collected packages: langchain-openai, langchain-experimental, langchain

   ---------------------------------------- 0/3 [langchain-openai]
   ------------- -------------------------- 1/3 [langchain-experimental]
   ------------- -------------------------- 1/3 [langchain-experimental]
   ------------- -------------------------- 1/3 [langchain-experimental]
   ------------- -------------------------- 1/3 [langchain-experimental]
   -------------------------- ------------- 2/3 [langchain]
   ---------------------------------------- 3/3 [langchain]

Successfully installed langchain-1.0.5 langchain-experimental-0.4.0 langchain-openai-1.0.2
Note: you may need to restart the kernel to use updated packages.

In [ ]:
pip install langchain langchain-openai langchain-experimental

Requirement already satisfied: langchain in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (1.0.5)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: langchain-openai in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (1.0.2)
Requirement already satisfied: langchain-experimental in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (0.4.0)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.4 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain) (1.0.4)
Requirement already satisfied: langgraph<1.1.0,>=1.0.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain) (1.0.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain) (2.11.9)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (0.4.41)
Requirement already satisfied: packaging<26.0.0,>=23.2.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (25.0)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (9.1.2)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-core<2.0.0,>=1.0.4->langchain) (4.15.0)
Requirement already satisfied: jsonpointer>=1.9 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.4->langchain) (3.0.0)
Requirement already satisfied: langgraph-checkpoint<4.0.0,>=2.1.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.0.1)
Requirement already satisfied: langgraph-prebuilt<1.1.0,>=1.0.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (1.0.2)
Requirement already satisfied: langgraph-sdk<0.3.0,>=0.2.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (0.2.9)
Requirement already satisfied: xxhash>=3.5.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph<1.1.0,>=1.0.2->langchain) (3.6.0)
Requirement already satisfied: ormsgpack>=1.12.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph-checkpoint<4.0.0,>=2.1.0->langgraph<1.1.0,>=1.0.2->langchain) (1.12.0)
Requirement already satisfied: httpx>=0.25.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (0.28.1)
Requirement already satisfied: orjson>=3.10.1 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (3.11.4)
Requirement already satisfied: requests-toolbelt>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (2.32.5)
Requirement already satisfied: zstandard>=0.23.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (0.24.0)
Requirement already satisfied: anyio in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (4.11.0)
Requirement already satisfied: certifi in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (2025.8.3)
Requirement already satisfied: httpcore==1.* in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (1.0.9)
Requirement already satisfied: idna in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (3.10)
Requirement already satisfied: h11>=0.16 in c:\users\admin\appdata\roaming\python\python312\site-packages (from httpcore==1.*->httpx>=0.25.2->langgraph-sdk<0.3.0,>=0.2.2->langgraph<1.1.0,>=1.0.2->langchain) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.1)
Requirement already satisfied: openai<3.0.0,>=1.109.1 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-openai) (2.7.2)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-openai) (0.12.0)
Requirement already satisfied: distro<2,>=1.7.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (0.12.0)
Requirement already satisfied: sniffio in c:\users\admin\appdata\roaming\python\python312\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (1.3.1)
Requirement already satisfied: tqdm>4 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from openai<3.0.0,>=1.109.1->langchain-openai) (4.67.1)
Requirement already satisfied: regex>=2022.1.18 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai) (2024.11.6)
Requirement already satisfied: langchain-community<1.0.0,>=0.4.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-experimental) (0.4.1)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.0.0)
Requirement already satisfied: SQLAlchemy<3.0.0,>=1.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.0.43)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.13.2)
Requirement already satisfied: dataclasses-json<0.7.0,>=0.6.7 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.6.7)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.11.0)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.4.1)
Requirement already satisfied: numpy>=1.26.2 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.26.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.22.0)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.26.1)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (0.9.0)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.0.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from langchain-classic<2.0.0,>=1.0.0->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.0.0)
Requirement already satisfied: python-dotenv>=0.21.0 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.1.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.4->langchain) (2.5.0)
Requirement already satisfied: greenlet>=1 in c:\users\admin\appdata\roaming\python\python312\site-packages (from SQLAlchemy<3.0.0,>=1.4.0->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (3.2.4)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\admin\anaconda3\envs\nlp_env\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json<0.7.0,>=0.6.7->langchain-community<1.0.0,>=0.4.0->langchain-experimental) (1.1.0)
Requirement already satisfied: colorama in c:\users\admin\appdata\roaming\python\python312\site-packages (from tqdm>4->openai<3.0.0,>=1.109.1->langchain-openai) (0.4.6)

In [132]:
agent.invoke("Which column has the highest average value?")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': 'df.mean().idxmax()'}`


TypeError: unsupported operand type(s) for +: 'int' and 'str'
Invoking: `python_repl_ast` with `{'query': "df.select_dtypes(include='number').mean().idxmax()"}`


PassengerIdThe column with the highest average value is `PassengerId`.

> Finished chain.

{'input': 'Which column has the highest average value?',
 'output': 'The column with the highest average value is `PassengerId`.'}

In [142]:
agent=create_pandas_dataframe_agent(
    llm, 
    df, 
    verbose=True,
    agent_type="openai-tools",
    allow_dangerous_code=True
    )

In [135]:
agent.run("How many rows are there")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': 'len(df)'}`


891There are 891 rows in the dataframe.

> Finished chain.

'There are 891 rows in the dataframe.'

In [136]:
agent.run("How many people have more than 3 siblings")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': "df[df['SibSp'] > 3].shape[0]"}`


30There are 30 people in the dataframe who have more than 3 siblings.

> Finished chain.

'There are 30 people in the dataframe who have more than 3 siblings.'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [137]:
df1=df.copy()

In [138]:
df1["Age"] = df1["Age"].fillna(df1["Age"].mean())

In [140]:
agent.run("How many rows in the age column are different")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': "df['Age'].nunique()"}`


88There are 88 different rows in the age column of the dataframe.

> Finished chain.

'There are 88 different rows in the age column of the dataframe.'

In [ ]:
df2=df1.copy()

In [ ]:
df2["Age_Multiplied"]=df1["Age"] * 2

In [ ]:
df2.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Multiplied
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,44.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,76.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,52.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,70.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,70.0

In [141]:
agent.run("Are the number of columns same in all the dataframe")

> Entering new AgentExecutor chain...

Invoking: `python_repl_ast` with `{'query': 'len(df.columns)'}`


12The dataframe `df` has 12 columns. If you have other dataframes to compare, please provide their details, and I can check if they have the same number of columns.

> Finished chain.

'The dataframe `df` has 12 columns. If you have other dataframes to compare, please provide their details, and I can check if they have the same number of columns.'